#!/usr/bin/env bash
# This script changes the resolution of localhost and facebook.com

# Check if the script is run as root
if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

# Backup the original hosts file
cp /etc/hosts /etc/hosts.bak

# Change the resolution of localhost and facebook.com
echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
