#!/usr/bin/env bash
# This script transfers a file from our client to a server using scp

# Check if the number of arguments is less than 4
if [ "$#" -ne 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign arguments to variables
FILE_PATH=$1
SERVER_IP=$2
USERNAME=$3
SSH_KEY_PATH=$4

# Use scp to transfer the file to the server's home directory
scp -i "$SSH_KEY_PATH" -o StrictHostKeyChecking=no "$FILE_PATH" "$USERNAME@$SERVER_IP:~/"

# Check if scp was successful
if [ $? -eq 0 ]; then
    echo "File $FILE_PATH has been successfully transferred to $USERNAME@$SERVER_IP:~/"
else
    echo "Failed to transfer file."
    exit 1
fi
