#!/usr/bin/env bash
# This script transfers a file from a client to a server using SCP

# Check if correct number of arguments is provided
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign arguments to variables
path_to_file="$1"
server_ip="$2"
username="$3"
ssh_key="$4"

# Transfer file to the server
scp -o StrictHostKeyChecking=no -i "$ssh_key" "$path_to_file" "$username@$server_ip":~/ 

# Check if file transfer was successful
if [ $? -eq 0 ]; then
    echo "File transfer successful"
else
    echo "File transfer failed"
fi
