#!/usr/bin/env bash
# Configures Nginx to serve a custom 404 page

# Update and install Nginx if it's not already installed
apt-get update
apt-get install -y nginx

# Create the custom 404 page content
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html

# Configure Nginx to use the custom 404 page
FILE="/etc/nginx/sites-available/default"

# Add or modify the custom 404 error page configuration
if ! grep -q "error_page 404 /custom_404.html;" $FILE; then
    sed -i '/server_name _;/a \\terror_page 404 /custom_404.html;' $FILE
    sed -i '/error_page 404 \/custom_404.html;/a \\tlocation = /custom_404.html {' $FILE
    sed -i '/location = \/custom_404.html {/a \\t\troot /usr/share/nginx/html;' $FILE
    sed -i '/root \/usr\/share\/nginx\/html;/a \\t\tinternal;' $FILE
    sed -i '/internal;/a \\t}' $FILE
fi

# Reload Nginx to apply the changes
nginx -s reload
