#!/usr/bin/env bash
# This script pings an IP address passed as an argument

# Check if an argument was passed
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
fi

# Ping the IP address 5 times
ping -c 5 $1
