#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process

PID=$(pgrep -f 4-to_infinity_and_beyond)
if [ -n "$PID" ]; then
    kill "$PID"
else
    echo "Process 4-to_infinity_and_beyond not found."
fi
