#!/usr/bin/env bash
# This script prints "To infinity and beyond" indefinitely every 2 seconds,
# and prints "I am invincible!!!" when receiving a SIGTERM signal.

trap 'echo "I am invincible!!!"' SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
